server.port=8081
server.address=127.0.0.1

# OAuth2 issuer
spring.security.oauth2.authorizationserver.issuer=http://localhost:8081

# Public client untuk Postman
spring.security.oauth2.authorizationserver.client.postman.registration.client-id=banking-postman
spring.security.oauth2.authorizationserver.client.postman.registration.client-authentication-methods[0]=none
spring.security.oauth2.authorizationserver.client.postman.registration.authorization-grant-types[0]=authorization_code
spring.security.oauth2.authorizationserver.client.postman.registration.redirect-uris[0]=https://oauth.pstmn.io/v1/browser-callback
spring.security.oauth2.authorizationserver.client.postman.registration.scopes[0]=account.read
spring.security.oauth2.authorizationserver.client.postman.registration.scopes[1]=transaction.read
spring.security.oauth2.authorizationserver.client.postman.registration.scopes[2]=transfer.write

spring.security.oauth2.authorizationserver.client.postman.require-authorization-consent=true
spring.security.oauth2.authorizationserver.client.postman.require-proof-key=true
spring.security.oauth2.authorizationserver.client.postman.token.access-token-time-to-live=10m

app.demo.customer-one-password=${DEMO_CUSTOMER_ONE_PASSWORD}
app.demo.customer-two-password=${DEMO_CUSTOMER_TWO_PASSWORD}


# $env:DEMO_CUSTOMER_ONE_PASSWORD = "Qwerty123"
# $env:DEMO_CUSTOMER_TWO_PASSWORD = "Qwerty123"
# $env:DB_PASSWORD = "Qwerty123"