FROM maven:3.9.12-eclipse-temurin-21 AS builder

WORKDIR /workspace

ARG MODULE

COPY . .

RUN mvn -pl ${MODULE} -am clean package -DskipTests


FROM eclipse-temurin:21-jre

WORKDIR /app

ARG MODULE

COPY --from=builder /workspace/${MODULE}/target/*.jar /app/app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/app/app.jar"]