spring.application.name=api-gateway
server.port=8080

# OAuth2 Resource Server
spring.security.oauth2.resourceserver.jwt.issuer-uri=${OAUTH2_ISSUER_URI:http://localhost:8081}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${OAUTH2_JWK_SET_URI:http://localhost:8081/oauth2/jwks}

# Redis
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

# Account Service route
spring.cloud.gateway.server.webflux.routes[0].id=account-service
spring.cloud.gateway.server.webflux.routes[0].uri=${ACCOUNT_SERVICE_URL:http://localhost:8082}
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/v1/customers/**,/api/v1/accounts/**

# Rate limit
app.rate-limit.max-requests=5
app.rate-limit.window=5m

# Actuator
management.endpoints.web.exposure.include=health,info


# Transaction Service
spring.cloud.gateway.server.webflux.routes[1].id=transaction-service

spring.cloud.gateway.server.webflux.routes[1].uri=${TRANSACTION_SERVICE_URL:http://localhost:8083}

spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/v1/transfers/**