apiVersion: v1
kind: Service

metadata:
  name: transaction-service
  namespace: banking

spec:
  type: ClusterIP

  selector:
    app: transaction-service

  ports:
    - name: http
      port: 8083
      targetPort: 8083
      protocol: TCP