spring.application.name=audit-service
server.port=8085

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/audit_db
spring.datasource.username=banking_admin
spring.datasource.password=${DB_PASSWORD}

# Flyway
spring.flyway.enabled=true

# Kafka
spring.kafka.bootstrap-servers=localhost:9094

spring.kafka.consumer.group-id=banking-audit-service
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=false

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Logging
logging.structured.format.console=logstash

# Actuator
management.endpoints.web.exposure.include=health,info