apiVersion: v1
kind: ConfigMap

metadata:
  name: banking-config
  namespace: banking

data:

  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"

  REDIS_HOST: redis
  REDIS_PORT: "6379"

  KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  AUTH_SERVICE_HOST: auth-service
  AUTH_SERVICE_PORT: "8081"

  ACCOUNT_SERVICE_HOST: account-service
  ACCOUNT_SERVICE_PORT: "8082"
  ACCOUNT_GRPC_HOST: account-service
  ACCOUNT_GRPC_PORT: "9092"

  TRANSACTION_SERVICE_HOST: transaction-service
  TRANSACTION_SERVICE_PORT: "8083"

  AUDIT_SERVICE_HOST: audit-service
  AUDIT_SERVICE_PORT: "8085"

  API_GATEWAY_PORT: "8080"