apiVersion: apps/v1
kind: Deployment

metadata:
  name: auth-service
  namespace: banking

spec:
  replicas: 1

  selector:
    matchLabels:
      app: auth-service

  template:

    metadata:
      labels:
        app: auth-service

    spec:

      containers:

        - name: auth-service

          image: banking-auth-service:1.0.0

          imagePullPolicy: IfNotPresent

          ports:
            - name: http
              containerPort: 8081
              protocol: TCP

          env:

            - name: SERVER_PORT
              value: "8081"

            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/auth_db

            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: banking-secret
                  key: DB_USERNAME

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: banking-secret
                  key: DB_PASSWORD

          readinessProbe:

            httpGet:
              path: /actuator/health
              port: 8081

            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 12

          livenessProbe:

            httpGet:
              path: /actuator/health
              port: 8081

            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 6

          resources:

            requests:
              cpu: 100m
              memory: 256Mi

            limits:
              cpu: "1"
              memory: 768Mi