apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: postgres
  namespace: banking

spec:
  serviceName: postgres

  replicas: 1

  selector:
    matchLabels:
      app: postgres

  template:
    metadata:
      labels:
        app: postgres

    spec:
      containers:

        - name: postgres

          image: postgres:17

          imagePullPolicy: IfNotPresent

          ports:
            - name: postgres
              containerPort: 5432
              protocol: TCP

          env:

            - name: POSTGRES_DB
              value: postgres

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: banking-secret
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: banking-secret
                  key: POSTGRES_PASSWORD

          args:
            - "-c"
            - "wal_level=logical"

            - "-c"
            - "max_replication_slots=10"

            - "-c"
            - "max_wal_senders=10"

          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data

          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U "$POSTGRES_USER" -d postgres

            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 6

          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U "$POSTGRES_USER" -d postgres

            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6

          resources:
            requests:
              cpu: 100m
              memory: 256Mi

            limits:
              cpu: "1"
              memory: 1Gi

  volumeClaimTemplates:

    - metadata:
        name: postgres-data

      spec:
        accessModes:
          - ReadWriteOnce

        resources:
          requests:
            storage: 5Gi