apiVersion: apps/v1
kind: Deployment

metadata:
  name: account-service
  namespace: banking

spec:
  replicas: 1

  selector:
    matchLabels:
      app: account-service

  template:
    metadata:
      labels:
        app: account-service

    spec:
      containers:
        - name: account-service

          image: banking-account-service:1.0.0
          imagePullPolicy: IfNotPresent

          ports:
            - name: http
              containerPort: 8082
              protocol: TCP

            - name: grpc
              containerPort: 9092
              protocol: TCP

          env:

            # =========================
            # Spring
            # =========================

            - name: SPRING_PROFILES_ACTIVE
              value: "dev"

            - name: SERVER_PORT
              value: "8082"

            - name: SERVER_ADDRESS
              value: "0.0.0.0"

            # =========================
            # PostgreSQL
            # =========================

            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/account_db

            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: banking-secret
                  key: DB_USERNAME

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: banking-secret
                  key: DB_PASSWORD

            # =========================
            # OAuth2 Resource Server
            # =========================

            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI
              value: http://auth-service:8081/oauth2/jwks

            # =========================
            # gRPC
            # =========================
            #
            # Dipakai jika application.properties mempunyai
            # grpc.server.port=${GRPC_PORT:9092}
            #

            - name: GRPC_PORT
              value: "9092"

          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8082

            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 60

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8082

            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8082

            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 6

          resources:
            requests:
              cpu: 100m
              memory: 256Mi

            limits:
              cpu: "1"
              memory: 768Mi