apiVersion: v1
kind: Service

metadata:
  name: account-service
  namespace: banking

spec:
  type: ClusterIP

  selector:
    app: account-service

  ports:
    - name: http
      port: 8082
      targetPort: 8082
      protocol: TCP

    - name: grpc
      port: 9092
      targetPort: 9092
      protocol: TCP